name: CI

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hdfs-version: [ "2.10.1", "3.2.3", "3.3.2" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        feature: [
          "hdfs_2_2",
          "hdfs_2_3",
          "hdfs_2_4",
          "hdfs_2_5",
          "hdfs_2_6",
          "hdfs_2_7",
          "hdfs_2_8",
          "hdfs_2_9",
          "hdfs_2_10",
          "hdfs_3_0",
          "hdfs_3_1",
          "hdfs_3_2",
          "hdfs_3_3",
        ]

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features ${{ matrix.feature }}

  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        feature: [
          "hdfs_2_2",
          "hdfs_2_3",
          "hdfs_2_4",
          "hdfs_2_5",
          "hdfs_2_6",
          "hdfs_2_7",
          "hdfs_2_8",
          "hdfs_2_9",
          "hdfs_2_10",
          "hdfs_3_0",
          "hdfs_3_1",
          "hdfs_3_2",
          "hdfs_3_3",
        ]

    steps:
      - uses: actions/checkout@v3

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features ${{ matrix.feature }} -- --nocapture
        env:
          RUST_LOG: DEBUG
          RUST_BACKTRACE: full
