name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We should support windows, but so far we can't build hadoop on it.
        # Visit [Tracking issue of windows support](https://github.com/Xuanwo/hdfs-sys/issues/17) for more details.
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        feature: [
          "hdfs_2_2",
          "hdfs_2_10",
          "hdfs_3_3",
        ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        id: setup_java
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Update Path for windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "${{ steps.setup_java.outputs.path }}\bin" >> $GITHUB_PATH
          echo "${{ steps.setup_java.outputs.path }}\jre\bin" >> $GITHUB_PATH
          echo "${{ steps.setup_java.outputs.path }}\jre\bin\server" >> $GITHUB_PATH

      - name: Build
        run: cargo build --features ${{ matrix.feature }}
      - name: Test
        run: cargo test --features ${{ matrix.feature }} -- --nocapture
        env:
          RUST_LOG: DEBUG
          RUST_BACKTRACE: full
          LD_LIBRARY_PATH: ${{ env.JAVA_HOME }}/lib/server:${{ env.JAVA_HOME }}/lib/amd64/server:${{ env.JAVA_HOME }}/jre/lib/server:${{ env.JAVA_HOME }}/jre/lib/amd64/server
